PrincetonUniversity/athena

src/hydro/srcterms/orbital_advection_srcterms.cpp
src/hydro/srcterms/rotating_system_srcterms.cpp
src/hydro/srcterms/shearing_box.cpp

The previous version had a bug in the hydro term for with the orbital advection in spherical polar coordinates. This PR gives a correct expression to the force from the OA system in the azimuthal direction. Some of `Real`  are rewritten by `const Real` or `const Real &` for the safety in `orbital_advection_srcterms.cpp`, .`rotating_system_srcterms.cpp`, and  `shearing_box.cpp`.

Fix a bug in OA hydro source term

---

src/bvals/bvals_base.cpp

According to #337, the shear boundary flag was not set properly for corner neighbors. This PR fix the bug. Even using this PR, neither the simulation results nor the limitation of the shear periodic boundary with SMR/AMR has any change.

Fix shearing boundary flag for corner neighbors

---

src/bvals/bvals_base.cpp

As @changoo pointed out, #378 has a typo. This PR is just a minor update to fix it.

fix typo in setting of shearing boundary flag

---

configure.py
inputs/hydro/athinput.quirk
src/hydro/calculate_velocity_differences.cpp
src/hydro/hydro.cpp
src/hydro/hydro.hpp
src/hydro/rsolvers/hydro/lhllc.cpp
src/hydro/rsolvers/mhd/hlld_iso.cpp
src/hydro/rsolvers/mhd/hlle_mhd.cpp
src/hydro/rsolvers/mhd/lhlld.cpp
src/main.cpp
src/pgen/quirk.cpp

These are newly proposed low-dissipation and Carbuncle-free extension of the HLLC (for hydro) and HLLD (for MHD) approximate Riemann solvers. The additional cost is only a few %.
Reference: Minoshima et al. 2021, arXiv:2108:04991 (JCoPh accepted)
Besides the new LHLLC/LHLLD solvers, I moved `OutputCycleDiagnostics` to be called before `UserWorkAfterLoop` in the finalizing process in main.cpp.
quirk.cpp is the Quirk test (Quirk 1994), in which a strong shock with odd-even perturbation propagates aligned to the grid. This odd-even perturbation should not grow physically, but standard high-resolution schemes such as HLLC/HLLD/Roe fail. The new LHLLC/LHLLD schemes are free from this issue. This test code checks the growth of the perturbation.
...

Low-dissipation HLLC/HLLD solvers (Minoshima et al. 2021)

---

src/bvals/bvals_base.cpp
src/pgen/strat.cpp

The `strat` problem is working only in the shearing box. It means that both `qshear` and `Omega_0` should be non-zero. However, those parameters are initialized in the ProblemGenerator function, which is not called in a restart run. This PR makes those parameters initialized in the InitUserMeshData function instead. 
P.S. I don't know why `bvals_base.cpp` is also updated. This fix was done at #379.

Fix of bug in the strat pgen for a restart run

---

src/pgen/gr_bondi.cpp

There was a small typo that broke the Bondi accretion problem by overwriting the black hole mass with the spin.

Fixed typo in GR Bondi problem generator

---

src/pgen/quirk.cpp
tst/regression/scripts/tests/hydro/hydro_carbuncle.py
tst/regression/scripts/tests/mhd/mhd_carbuncle.py

Short addition to #380. Although after reviewing Quirk (1994), I am not sure this problem generator examines the Carbuncle instability (section 2.4 of that paper), but instead is a test of LHLLC and LHLLD's ability to avoid the Odd-Even decoupling (section 2.6)?

Add hydro and MHD regression tests for quirk.cpp

---

vis/python/athena_read.py
vis/python/plot_slice.py
vis/python/plot_spherical.py

- Newer versions of h5py read strings as by strings and require being encoded to enable/disable options, prefer utf-8 over ascii
- Stream plots from single precision data fail without recasting grid limits, so recast cell coordinates into uniform data
- prefer explicit objects over `plt.` usage with figures, axes, etc. 
- plots assume rectangular grid, add polar projection for cylindrical plots
- expose num_ghosts as a parameter
- resolve https://github.com/PrincetonUniversity/athena/issues/393
Commits should have been split up but want to get feedback to determine if these changes are useful upstream
Ad hoc testing on current data, appears to work for cylindrical slice

Update plotting slices and add polar projection view 

---

src/outputs/outputs.cpp
src/outputs/outputs.hpp

Sometimes one would like to cherrypick variables to be output to reduce output sizes when a lot of variables are output by default. But outputting variables into multiple files generates unmanageable amount of files (plus there will be redundant information such as the mesh coordinates).
This pull request allows users to provide a list of variables in a form of comma-delimited string in athinput files, e.g.,
```
variable = d,p,E,m,bcc
```
It changes `OutputType` to look for occurrences instead of exact matches.
...

Allow cherrypicking variables to be output

---

src/outputs/outputs.cpp
src/outputs/outputs.hpp

This PR adds "dcycle" option in the <output> block in input. "dcycle" is an integer number, and the code outputs data at every "dcycle" step. "dt" and "dcycle" are exclusive.
This feature is useful for some problems with drastic change in time scale. A particular example is self-gravitational collapse like star formation.

Added "dcycle" option to output data at constant cycle intervals

---

src/bvals/bvals_refine.cpp

Tiny change that fixes #419.
This should have only ever affected multidimensional relativistic SMR/AMR calculations, with an error that scales as Lorentz factor. It doesn't even violate conservation. Some passive scalar might have gotten trapped or moved slightly too quickly at a coarse-fine boundary relative to the mass flux.

Corrected density used in relativistic passive scalar prolongation

---

src/hydro/srcterms/rotating_system_srcterms.cpp

The rotating frame does not support spherical polar coordinates in 1D, and prior to this PR would result in a segfault. This PR makes it so that an appropriate error message is raised for this case.

Added error message for rotating frame in 1d spherical polar

---

vis/python/athena_read.py

`athena_read.py` was missing a pair of parentheses, resulting in erroneous values for `x1v` being returned. This only affected Schwarzschild coordinates, which are rarely used in production.

Tiny fix for reading Schwarzschild .athdf files

---

src/pgen/gr_torus.cpp

There was a small typo brought to my attention by @pdmullen. The result was initial equilibrium tori had slight inward radial velocities close to the black hole. Other problem generators are unaffected. The bug was introduced in 072634e8.

Fixed typo in gr_torus problem generator

---

src/task_list/time_integrator.cpp

In AddSourceTermsHydro, it is supposed to impose source functions not only on hydro variables but also on passive scalars. If we change passive scalars in AddSourceTermsHydro, SEND_SCLR and SETB_SCLR need to wait for the execution of SRCTERM_HYD rather than INT_SCLR. This PR fixes the dependencies. 
The name of AddSourceTermsHydro is confusing. I think that we should make a new function as AddSourceTermsScalars or rename the function.

fix dependency of passive scalar boundary communication

---

src/eos/adiabatic_hydro.cpp
src/hydro/srcterms/hydro_srcterms.cpp
src/hydro/srcterms/hydro_srcterms.hpp
src/task_list/task_list.hpp
src/task_list/time_integrator.cpp

As discussed in 49d491e1837a578ebf29216c7cdade8e842cb9fc, the name of source functions were misunderstanding. This PR renames the functions as below. 
HydroSourceTerms
`void HydroSourceTerms::AddHydroSourceTerms`
=> `void HydroSourceTerms::AddSourceTerms`
TaskList
`TaskID SRCTERM_HYD`
=> `TaskID SRC_TERM`
`TaskStatus TimeIntegratorTaskList::AddSourceTermsHydro`
=> `TaskStatus TimeIntegratorTaskList::AddSourceTerm`
If I just omit `Hydro` from the names, two functions in HydroSourceTerms and TaskList have the same name. To avoid the duplication, I rename one in singular form and the other in plural form. It could be still confusing, but It would be OK.
This PR has passed the regression tests and meet the Athena++ style. I found that e08dd974808fed05b9d7709f63bedfb42b885224 does not meet the …

Rename Source Functions

---

src/outputs/outputs.cpp

Closes #436 
Tested on my machine with problem `linear_wave` configured as followed:
`python configure.py --prob=linear_wave --cxx=clang++ --cflag='-arch arm64' -debug -hdf5`
Edited `athinput.linear_wave1d`, added hdf5 output and `,uov` to variable.
Code runs without producing error and the uov is output as intended.

Fix bug specifying uov output

---

src/fft/turbulence.cpp

Just stumble upon this bug that is only triggered for decaying turbulence (turb_flag == 1).
When `turb_flag == 1`, `fv_new_` would be pointing to random address and the destructor of `TurbulenceDriver` would attempt to access and free `fv_new_[nv]`.

Initialize pointer fv_new_ to nullptr

---

src/mesh/mesh.cpp
src/task_list/sts_task_list.cpp
src/task_list/time_integrator.cpp

I noticed something wrong with the passive scalars near refinement boundaries in an AMR calculation. After digging through the code, I realized the scalars were not perfectly paralleling the hydro quantities with regard to primitive vs. conserved coarse buffers. In particular, calls to `HydroBoundaryVariable::SwapHydroQuantity` were followed by the appropriate setting of `var_cc` in the scalars' `CellCenteredBoundaryVariable`, but the subsequent setting of `coarse_buf` done by `HydroBoundaryVariable::SelectCoarseBuffer` was omitted. This occurs 7 times in `mesh.cpp`, 4 times in `time_integrator.cpp`, and 2 times in `sts_task_list.cpp`.
This pull request adds in the missing logic in all 13 cases. I don't know if this is strictly necessary in all cases, but it doesn't seem like this can …

Fixed passive scalar + AMR bug

---

src/eos/adiabatic_mhd_sr.cpp

This is a small fix that only affects SRMHD. There was a bug that occurs only when there is some mild variable inversion failure, with the incorrect conserved <-> primitive relation being applied in the case of nonvanishing magnetic field. This wouldn't be covered by any test problems, since there should never be any variable inversion failures there.

Fixed bug in fixup routine for SRMHD

---

src/main.cpp
src/outputs/outputs.cpp
src/outputs/restart.cpp

Makes command line changes equivalent to input file changes. Closes #451. Can you check @EdwinChan ? I just removed the `if (iarg_flag == 1)` check for the `Forward/RollbackNextTime()` calls in `main.cpp`, which I am pretty sure is safe in all cases but not 100% positive. 
Also closes #310, by skipping the initial condition output if `next_time > start_time`. This was one of two suggested changes; see discussion in #311. The alternative is to stop overriding `next_time` when the IC is outputted, in other words "keep `next_time` after the initial output."
---
#451 had many other comments and suggestions, which should be opened as separate issues if we want to pursue any of them:
```
./outputs/outputs.cpp:137:      op.next_time = pin->GetOrAddReal(op.block_name,"next_time", pm->time);
``` …

Apply output time cadence changes even if no input file is provided during restarts

---

src/mesh/mesh.cpp
src/outputs/io_wrapper.cpp
src/outputs/io_wrapper.hpp
src/outputs/restart.cpp

This is a patch to fix the error in restart reported in #449. The original implementation loads all MeshBlocks at once from a restart file. This version reads the data one by one in order to avoid hitting the 2GB limit of MPI_File_read.
I tested the code by changing the number of processes and it seems working. However, as I tested only for a few steps and Athena++ does not support bitwise reproducibility anyway, I could not cover sufficient test cases. So I would like to request @Edwinchan and @kahoooo to test it thoroughly.  Also, this version can be slower than the original as it calls MPI_File_read many times.

Fixing the restart error reported in #449

---

src/pgen/disk.cpp

As pointed out in #430, disk.cpp has a bug. 
This PR just modifies the bug, `x3v(i)` -> `x3v(k)`.

fix a bug in disk.cpp

---

src/fft/turbulence.cpp

When `rseed >= 0`, the turbulent power spectrum is generated with a global random number sequence, such that the perturbed velocity field is independent of the Meshblock configuration. However, current implementation does not give identical perturbation when the total number of cells (i.e., Mesh size) is changed. For example, the below figure plots the velocity perturbations in z=0 plane initialized with `rseed = 0`, using 32^3 (upper panels) and 64^3 (lower panels) Mesh (using `src/pgen/turb.cpp`), showing that the turbulent velocity field is different for different Mesh size.
This can be fixed by drawing random numbers only when the wavenumber is in the range specified by `nlow` and …

Make turbulent velocity field resolution independent

---

src/hydro/rsolvers/mhd/hlld.cpp
src/hydro/rsolvers/mhd/hlld_iso.cpp
src/hydro/rsolvers/mhd/lhlld.cpp

The SMALL_NUMBER constant was used to detect degeneracy conditions in the HLLD-series Riemann solvers (HLLD, LHLLD, and isothermal HLLD). The previous value 10^-8 was too small and failed in some situations with strong magnetic fields. This PR changes this number to 10^-4, which is more robust.
Note that the number in HLLD and LHLLD are used for comparing variables with the pressure dimension, while in the isothermal HLLD it is for comparing variables with the velocity dimension. Therefore, a different value may be more optimal for the isothermal HLLD solver.
A slow-shock with perturbation. The top panel is the original implementation and the bottom is the new one. The unphysical explosions in the original are fixed with this change.

Change SMALL_NUMBER to 10^-4 in the HLLD-series Riemann solvers

---

src/bvals/bvals.cpp
src/bvals/bvals.hpp

STS only sends/receives a subset of variables and fluxes depending on which diffusive physics are enabled.  For example, for an isothermal calculation invoking STS for Ohmic diffusion, only field variables/fluxes are communicated inside the `SuperTimeStepTaskList`.
When a shearing box overhaul in PR #342 made STS compatible with shearing box, this communication strategy was not reflected in the shearing box specific codebase.  @zhuzh1983 reported a hang for a calculation using an (1) isothermal EOS, (2) ambipolar diffusion, (3) STS, and (4) MPI.   I find that the changes in this PR remove the deadlock.  
Specifically, after PR #342, the function `StartReceivingShear` was not modified to reflect the aforementioned communication design: …

Fix Shearing Box + STS Hang

---

src/reconstruct/reconstruction.cpp

Adding an error trap following Shinsuke Takasao's report that using the 4th order algorithm for hydro and the second order CT algorithm with RK4 + xorder=4 was only zeroth order, and RK4 + xorder = 4c was first order.

Add trap for MHD with xorder=4,4c selections

---

src/parameter_input.cpp

Error messages in parameter_inpit.cpp stated they were raised in the wrong function.
...

Fixed Typo in Error Messages

---

src/reconstruct/reconstruction.cpp

Here's a small fix to what appears to be an unintentional bug when using curvilinear coordinates with PPM reconstruction.
In `src/reconstruct/reconstruction.cpp`, a stray reference leads to changing the cell-volume-averaged radius (`x1v`) to the geometric cell-midpoint radius ( halfway between adjacent `x1f`s) when reconstruction variables are pre-computed. 
I cleaned up these lines a bit since I was digging around there.

Fix x1v for Curvilinear+PPM

---

src/hydro/hydro_diffusion/viscosity.cpp

This is a simple fix for a divide-by-zero I stumbled upon. I think it is just a missed edge case when viscosity is used in conjunction with 3d spherical polar extending to the pole x2min=0.0. The offending code is line 398 of viscosity.cpp:
```
void HydroDiffusion::FaceYdz(const int k, const int j, const int il, const int iu,
const AthenaArray<Real> &prim, AthenaArray<Real> &len) {
if (pmb_->pmy_mesh->f3) {
#pragma omp simd
for (int i=il; i<=iu; ++i) {
len(i) = pco_->h32f(j)
* ( prim(IM3,k,j,i)/pco_->h32v(j) - prim(IM3,k,j-1,i)/pco_->h32v(j-1) )
/ pco_->h2v(i) / pco_->dx2v(j-1)
// KGF: add the off-centered quantities first to preserve FP symmetry
+ 0.5*(    (prim(IM2,k+1,j,i) + prim(IM2,k+1,j-1,i))
- (prim(IM2,k-1,j,i) + prim(IM2,k-1,j-1,i)) )
/ pco_->h31v(i)
/ pco_->h32f(j) / …
```

bugfix for viscosity + 3d polar boundary condition

---

src/coordinates/cylindrical.cpp
src/coordinates/spherical_polar.cpp
src/mesh/mesh_refinement.cpp
src/mesh/mesh_refinement.hpp
src/pgen/field_loop_poles.cpp

The changes follow from pull request #582: Divergence-preserving prolongation of coarse/fine shared face-centered fields for 3D spherical polar grids. The divergence-preserving interpolation is now also triggered for 3D cylindrical grids. The condition for this is now evaluated outside the loops for performance. I also added area-averaged coordinates for spherical polar and cylindrical coordinates, which are used for MHD with AMR. Finally, I changed how the total cells in the field loop poles problem generator are computed: from a loop to using the function `MeshBlock::GetNumberOfMeshBlockCells()`.
The main changes were required to preserve the divergence of the magnetic field during refinement of curvilinear grids.
Interpolation in ProlongateSharedFieldX functions now preserves the …

Divergence-preserving prolongation of coarse/fine shared face-centered fields for 3D spherical polar and cylindrical grids 

---

vis/python/athena_read.py

athena_read allocates unnecessarily large amount of memory for each quantity, rendering file reading unnecessarily slow or even impossible. (see #586)
```
if s > 1:
if nx1 > 1:
block_data = np.repeat(block_data, s, axis=2)
if nx2 > 1:
block_data = np.repeat(block_data, s, axis=1)
if nx3 > 1:
block_data = np.repeat(block_data, s, axis=0)
data[q][kl_d:ku_d, jl_d:ju_d, il_d:iu_d] = block_data[kl_s:ku_s,
jl_s:ju_s,
il_s:iu_s]
```
Allocates an array of size ( 2^s nx1, 2^s nx2, 2^s nx3), in 3D, whatever the selected size of the domain.
```
if s > 1:
if nx1 > 1:
block_data = np.repeat(block_data, s, axis=2)[:,:,il_s:iu_s]
if nx2 > 1:
block_data = np.repeat(block_data, s, axis=1)[:,jl_s:ju_s,:]
if nx3 > 1:
block_data = np.repeat(block_data, s, axis=0)[kl_s:ku_s,:,:]
data[q][kl_d:ku_d, jl_d:ju_d, …
```

 Fixes athena_read's unnecessarily large memory allocation

---

src/bvals/bvals.cpp
src/bvals/bvals.hpp

Alternative to #585 suggested by @tomidakn that might be more narrowly-tailored. 
See https://github.com/PrincetonUniversity/athena/issues/571 and https://github.com/PrincetonUniversity/athena/discussions/569.
Ideally, we would want to check the refinement restrictions only at the beginning of the simulation and after refinement (if adaptive)-- but I am not really sure I implemented this check correctly. @tomidakn am I correct in interpreting `nblx3 = pmy_mesh_->nrbx3*(1L << level);` as  "the maximum possible number of MeshBlocks in the x3 direction across the entire mesh at the same level of refinement as the current MeshBlock"? So that the following traverses the root `MeshBlockTree` to check that every MeshBlock at the same (x1, x2) logical location as the current MeshBlock (which is …

Add better exclusion for MHD+shearing box+SMR with refinement in x3 dir at shearing boundary

---

vis/python/plot_mesh.py

The method `gca()` of a [`Figure` object](https://matplotlib.org/3.6.3/api/figure_api.html) does not accept keyword arguments anymore since Matplotlib 3.6.
1. Minor change: The python script `~/vis/python/plot_mesh.py` needs to be revised according to Matplotlib API change.

Matplotlib 3.6 API change.

---

tst/regression/run_tests.py

- [ x] My code follows the Athena++ [Style Guide](https://github.com/PrincetonUniversity/athena/wiki/Style-Guide)
Stampede3 uses `ibrun` instead of `mpirun`, this PR accommodates that.

Add ibrun to mpirun options

---

Makefile.in
configure.py
src/coordinates/cartesian.cpp
src/coordinates/coordinates.cpp
src/coordinates/coordinates.hpp
src/coordinates/cylindrical.cpp
src/coordinates/gr_user.cpp
src/coordinates/kerr-schild.cpp
src/coordinates/minkowski.cpp
src/coordinates/schwarzschild.cpp
src/coordinates/spherical_polar.cpp
src/mesh/mesh_refinement.cpp
src/mesh/meshblock.cpp

As discussed in #595, I changed the Coordinates classes so that only one file is selected by the configuration script. Now there are no derived classes but just one Coordinates class. Default functions (Cartesian) are implemented using "__attribute__((weak))", and only different parts are implemented in each file.
This can save some compilation time and also is more GPU friendly. This change should not affect any user experience.

Redesigning Coordinates classes

---

src/coordinates/schwarzschild.cpp

x1-array was accidentally used in place of x2-array, but indexed with j. As cell widths only affect relativity for timestep purposes, and as most simulations use horizon-penetrating coordinates, this had little effect except when non-square MeshBlocks would cause crashes.
Fixes #613

Fixed Schwarzschild cell-width calculation

---

configure.py
src/chemistry/network/none.cpp

The original code caused a linking error of outputs.cpp and history.cpp with icpc when compiled with -O0 (configure with `--cxx icpc -d`) because ChemNetwork::species_names (a static const member) was declared but not set. The error did not appear with -O3, possibly because it was optimized out. (I do not know why gcc has no problem with this.)
This fix adds none.cpp for an empty chemical network and initialize species_names.
- [] All new and existing tests passed.

Fixing a linking error for chemistry with no network

---

src/hydro/rsolvers/mhd/hlld.cpp
src/hydro/rsolvers/mhd/lhlld.cpp

It turned out that we should not remove the double-star states even when the normal magnetic field bx is very weak. If this branch is selected when bx is actually non-zero, it may return unphysical flux. In fact, this check is not mentioned in Miyoshi & Kusano 2005 but already existed in the old Athena, 
I do not think this has affected many people, as this is problematic only when the magnetic fields are very weak and the flow is not smooth. The probability that this branch is selected is very low in a realistic flow.
Thanks to Kazunari Iwasaki.

Removed a degeneracy check from the HLLD and LHLLD Riemann Solvers.

---

inputs/hydro/athinput.turb
src/mesh/mesh.cpp
src/pgen/chem_turb.cpp
src/pgen/turb.cpp
tst/regression/scripts/tests/turb/turb_3d.py

1. Initialized `turb_flag` in the Mesh constructor by reading it from the problem input under the `turbulence` block (with the default being 0). No need to initialize it in the pgen files. 
This closes #634

Initialized turb_flag in the Mesh constructor

---

inputs/hydro/athinput.mignone_radial
src/coordinates/spherical_polar.cpp

Add fatal error for 1d spherical polar problems if the x2 limits are not symmetric about PI/2. This addresses the raised issue #354. This also updates the x2-limits for the 1d mignone radial test to be symmetric so that the regression test doesn't conflict with this PR. 
tested against regression tests involving spherical polar coordinates
does not address associated non-zero vtheta in 1d spherical in any way
Closes #354

Throw fatal runtime error for asymmetric x2 bounds for 1D spherical-polar mesh

---

src/bvals/cc/nr_radiation/bvals_rad.cpp
src/bvals/cc/nr_radiation/bvals_rad.hpp
src/mesh/mesh.cpp
src/nr_radiation/angulargrid.cpp
src/nr_radiation/radiation.cpp
src/nr_radiation/radiation.hpp
src/task_list/im_rad_task_list.cpp
src/task_list/im_rad_task_list.hpp
src/task_list/im_radit_task_list.cpp

Fix boundary conditions for implicit radiation; add the option of pure radial rays and function for user-defined frequency grid

---

src/athena.hpp
src/mesh/amr_loadbalance.cpp
src/mesh/mesh.cpp
src/mesh/mesh.hpp
src/mesh/mesh_refinement.cpp
src/mesh/mesh_refinement.hpp
src/multigrid/multigrid.hpp

This is to fix the divergence error with AMR reported in #617.
When a MeshBlock contacting a finer MeshBlock is refined, the original code refined normal B-fields on the shared face by interpolating the coarser fields, but they do not exactly match the existing finer fields on the already refined neighbor MeshBlock. With this commit, the shared face fields are copied from the finer MeshBlock, hence enforcing the divergence B constraint.

Fixing divergence error with AMR (Issue #617)

---

src/units/units.hpp

Very minor changes:
1. Changed solar_mass_cgs from 1.9891e33 to 1.9884099e33 to agree with value used in Astropy.
2. Changed yr_cgs from 3.155815e7 to 3.15576e7 to agree with value used in Astropy and the FITS standard of using a Julian year of exactly 365.25 days.
3. Changed pc_cgs from 3.085678e18 to 3.08567758e18 to agree with value used in Astropy.

Update constant values in units.hpp to agree with values in Astropy and FITS standard

---

inputs/mhd/athinput.rj2a

There was no reference to a problem in the athinput.rj2a input file. I have added the `--prob=shock_tube` argument.
The source code hasn't been changed.
There was no reference to a problem in the `athinput.rj2a` input file. I have added the `--prob=shock_tube` argument.
This issue made it impossible to run the RJ2a problem simply; forcing the user to dive in the code to check where this problem was generated.
You may want to categorize major vs. minor changes and list them:
1. Minor change : modify an input file
I followed the procedure described in the Athena Wiki for the 1D MHD problem set up, with the athinput.rj2a file. the output was the following 
```bash
python3 configure.py …
```

Add missing problem reference in RJ2A input file
